### PR TITLE
Feature/nirmal agnihotri/875809796 add navbar

### PR DESCRIPTION
**Pull request by NirmalAgnihotri**
### Administrative Info

Monday Board ID: 851212620
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- TODO

### Testing

How did you confirm your changes worked?

- TODO

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| ----------------------- |
| [TODO Screenshot Link]  |

### CODE REVIEW

**Review by sblumin — APPROVED** [review]
Looks good to me! Be checking for merge conflicts and make sure to resolve all of them if needed

**Review by sblumin — CHANGES_REQUESTED** [review]
The circleCI test is failing to due to this message `Invariant failed: You should not use <Link> outside a <Router>` I see in Navbar.js you use <Link> outside of a <Router>. Can you look into this and see if you make this fix so circleCI won't fail?

**Review by sblumin — APPROVED** [review]
LGTM

**Review by StephenTan12 — APPROVED** [review]
Not sure whether the inconsistency of semicolons in the import statements will affect anything, but other than that, LGTM!

**Pull request merged**
