### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by sblumin**
### Administrative Info

Monday Board ID: 851212620
Task ID: 1010524604

### Changes

What changes did you make?

Removed old template README and replaced it with a new README

### Testing

How did you confirm your changes worked?

Previewed README through Github UI

### Confirmation of Change

View the updated README with markdown in my branch if you can't see it through the PR
here's a preview
Screen Shot 2021-01-29 at 3 05 08 PM

### CODE REVIEW

**Review by wllmwu — APPROVED** [review]
Looks LGTM to me

**Review by emmanuelclflores — APPROVED** [review]
LGTM

**Review by StephenTan12 — APPROVED** [review]
LGTM!

**Review by NirmalAgnihotri — COMMENTED** [review]
Looks great! Maybe add a section about the testing that just has the npm run test command to run the JEST tests.

**Comment by ryanbuui** [comment]
LGTM

**Review by ryanbuui — APPROVED** [review]
LGTM

**Review by nicolaswl — APPROVED** [review]

**Pull request merged**
